
modLoader="javafml"
loaderVersion="${ForgeVR}"
license="All rights reserved"
[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
credits="Thanks for me and me and... also me <3"
authors="Sasai_Kudasai_BM" 
description='''
Some... description?
Is it really needed?
'''
[[mods]]
modId="lonely"
version="0.0.1"
displayName="Lonely"
credits="Thanks for me and me and... also me <3"
authors="Sasai_Kudasai_BM" 
description='''
Some... description?
Is it really needed?
'''

[[dependencies.lonely]]
    modId="minecraft"
    mandatory=true
    versionRange="${MCVR}"
    ordering="NONE"
    side="BOTH"
[[dependencies.lonely]]
    modId="forge"
    mandatory=true
    versionRange="${ForgeVR}"
    ordering="NONE"
    side="BOTH"

[[dependencies.skds_core]]
    modId="forge"
    mandatory=true
    versionRange="${ForgeVR}"
    ordering="NONE"
    side="BOTH"

[[dependencies.skds_core]]
    modId="minecraft"
    mandatory=true
    versionRange="${MCVR}"
    ordering="NONE"
    side="BOTH"
